### ISSUE TITLE
Changing TFM to multi-target

### ISSUE THREAD

**Issue by ChristineBoersen** [Jehoel/AsyncDataAdapter#2]
Is there any way you can change your projects to target multiple frameworks (should hopefully just be one line in the csproj)
to 
`
<TargetFrameworks>net5.0;netstandard2.0</TargetFrameworks>
`
This way the consumer can use whichever is latest/best for their purpose (dotnetcore vs framework)

Thanks,
Christine

**Comment by daiplusplus** [comment]
...but a .NET Standard 2.0 assembly can be used by people using .NET Framework 4.7.2, .NET Core 3+, and .NET Core 5. Are you having problems referencing it?

Other than nullable annotations (which aren't used in this project yet), there isn't any functionality that's platform-specific.

**Comment by ChristineBoersen** [comment]
It consumes properly under net50 without any issues as it is currently.

If you do what I was suggesting above, it outputs BOTH net50 and netstandard20 dlls (and dependency trees, etc).  It places each build in separate directories

Then, when consuming the nuget package msbuild tooling hooks everything up to the right version (whatever is highest) that is compatible with the project consuming it.

[https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-a-target-framework](url)

**Comment by daiplusplus** [comment]
Yes, however _as far as I know_  at present there is no need for platform-specific assemblies so there is no added value for consumers by specifically targeting .NET Core and .NET5+ and .NET Framework in addition to targeting .NET Standard 2.0 compared to targeting .NET Standard 2.0 alone.

If I do add nullable annotations then yes, multi-targeting will be useful - but until then there’s no point... unless you can think of any?

> If you do what I was suggesting above, it outputs BOTH net50 and netstandard20 dlls (and dependency trees, etc). It places each build in separate directories. 
> Then, when consuming the nuget package msbuild tooling hooks everything up to the right version (whatever is highest) that is compatible with the project consuming it.

This alone is not a compelling reason. It doesn’t create any benefit. The project targets .NET Standard 2.0 *because that’s what .NET Standard is for*.

I’m closing this for now - but if there is a compelling reason to use multi-targeting that adds value to the NuGet package then please reply and I’ll reopen this.
